
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultListModel;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ga1ahad
 */
public class kasir extends javax.swing.JFrame {

    /**
     * Creates new form kasir
     */
    
    //MODEL
    DefaultListModel d_nama=new DefaultListModel();
    DefaultListModel d_satuan=new DefaultListModel();
    DefaultListModel d_banyak=new DefaultListModel();
    DefaultListModel d_subtot=new DefaultListModel();
    
    public kasir() {
        initComponents();
        this.setLocationRelativeTo(null);
        print.setLocationRelativeTo(null);
    }
    int i = 0;
    int total = 0;
    int babel = 0;
    int g_ppn,g_bkp,g_dpp,g_disc;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        print = new javax.swing.JDialog();
        txt_receipt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_waktu = new javax.swing.JLabel();
        txt_kasir = new javax.swing.JLabel();
        txt_kasir2 = new javax.swing.JLabel();
        txt_receipt1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampil = new javax.swing.JTextArea();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txt_sub = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_net = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_cash = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_change = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        txt_dpp = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txt_bkp = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txt_disc = new javax.swing.JLabel();
        txt_ppn = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        pilih_buku = new javax.swing.JComboBox<>();
        jumlah_buku1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        satuan_1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        total_1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sub_totalitas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        net_total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        kode_buku1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        tambah = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        sub_total = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        total_list = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        banyak_buku = new javax.swing.JList<>();
        hapus = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        sub_totalitas1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        receipt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        disk = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ppen = new javax.swing.JTextField();

        print.setTitle("Print");
        print.setAlwaysOnTop(true);
        print.setMaximumSize(new java.awt.Dimension(300, 600));
        print.setMinimumSize(new java.awt.Dimension(300, 600));
        print.setPreferredSize(new java.awt.Dimension(300, 600));
        print.setSize(new java.awt.Dimension(300, 650));
        print.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_receipt.setText("Receipt");
        print.getContentPane().add(txt_receipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel2.setText("JL. GAJAH MADA 109 JAKARTA");
        print.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel3.setText("NPWP / PKP : 01.305.681.7-092.000");
        print.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel4.setText("TGL. PENGUKUHAN : 02-04-2012");
        print.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        print.getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 570, 420, -1));

        jLabel5.setText("PT GRAMEDIA ASRI MEDIA");
        print.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel10.setText("GRAMEDIA BANDUNG MERDEKA");
        print.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txt_waktu.setText("Waktu");
        print.getContentPane().add(txt_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txt_kasir.setText("Kasir");
        print.getContentPane().add(txt_kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        txt_kasir2.setText("Receipt. No :");
        print.getContentPane().add(txt_kasir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txt_receipt1.setText("** SALE **");
        print.getContentPane().add(txt_receipt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));
        print.getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 104, 420, -1));

        tampil.setEditable(false);
        tampil.setColumns(20);
        tampil.setRows(5);
        tampil.setMaximumSize(new java.awt.Dimension(260, 400));
        jScrollPane1.setViewportView(tampil);

        print.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 380, 160));
        print.getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 200, 420, -1));

        jLabel1.setText("Sub Total");
        print.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txt_sub.setText("sub");
        print.getContentPane().add(txt_sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        jLabel21.setText("Net Total");
        print.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        txt_net.setText("net");
        print.getContentPane().add(txt_net, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        jLabel23.setText("CASH");
        print.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        txt_cash.setText("cash");
        print.getContentPane().add(txt_cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel24.setText("Change back (CASH)");
        print.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        txt_change.setText("change");
        print.getContentPane().add(txt_change, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));
        print.getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 380, 420, -1));

        jLabel25.setText("BEBAS PPN :   0");
        print.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        txt_dpp.setText("dpp");
        print.getContentPane().add(txt_dpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        jLabel27.setText("DPP :");
        print.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel28.setText("PPN :");
        print.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, -1, -1));

        txt_bkp.setText("bkp");
        print.getContentPane().add(txt_bkp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel29.setText("BKP :");
        print.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        jLabel30.setText("Disc :");
        print.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        txt_disc.setText("disc");
        print.getContentPane().add(txt_disc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        txt_ppn.setText("ppn");
        print.getContentPane().add(txt_ppn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));
        print.getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 500, 420, -1));

        jLabel26.setText("TERIMA KASIH");
        print.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, -1, -1));

        jLabel31.setText("Beli Buku, Click");
        print.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, -1));

        jLabel32.setText("www.gramedia.com");
        print.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penjualan PT. GRAMEDIA ASRI MEDIA");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        pilih_buku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- none -", "Silence by Akiyoshi Rikako", "Jerusalem the Biography by Simon Sebag Montefiore", "Guns, Germ and Steel by Jared Diamond", "The Human Story by James C. Javis", "Pulang by Tere Liye", "Art of Dakwah by Felix Siauw", "Pemrograman C dan C++ by Adam Mukharil Bachtiar" }));
        pilih_buku.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pilih_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilih_bukuActionPerformed(evt);
            }
        });

        jumlah_buku1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jumlah_buku1StateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel6.setText("Kode Buku");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel7.setText("Nama Buku");

        satuan_1.setEditable(false);
        satuan_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satuan_1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel8.setText("Harga Satuan");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel9.setText("APLIKASI PENJUALAN");

        total_1.setEditable(false);
        total_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel11.setText("Sub Total");

        sub_totalitas.setEditable(false);
        sub_totalitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_totalitasActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel13.setText("Net Total");

        net_total.setEditable(false);
        net_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                net_totalActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel17.setText("CASH");

        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Bayar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kode_buku1.setEditable(false);
        kode_buku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_buku1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel16.setText("Qty");

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel19.setText("Harga Total");

        kembalian.setEditable(false);
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel22.setText("Change back (CASH)");

        list.setBackground(new java.awt.Color(242, 241, 240));
        jScrollPane2.setViewportView(list);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        sub_total.setBackground(new java.awt.Color(242, 241, 240));
        jScrollPane3.setViewportView(sub_total);

        total_list.setBackground(new java.awt.Color(242, 241, 240));
        jScrollPane4.setViewportView(total_list);

        banyak_buku.setBackground(new java.awt.Color(242, 241, 240));
        jScrollPane5.setViewportView(banyak_buku);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel12.setText("Tanggal");

        sub_totalitas1.setEditable(false);
        sub_totalitas1.setText("Karina Destriane");
        sub_totalitas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_totalitas1ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel14.setText("Kasir");

        tanggal.setEditable(false);
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel15.setText("No Receipt");

        receipt.setEditable(false);
        receipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel18.setText("Diskon");

        jLabel20.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel20.setText("PPN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(124, 124, 124)
                                .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addGap(30, 30, 30)
                                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sub_totalitas, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(net_total, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(90, 90, 90)
                                .addComponent(receipt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(9, 9, 9)
                                            .addComponent(disk, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel20)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ppen))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(8, 8, 8)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14))
                                        .addGap(111, 111, 111)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sub_totalitas1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                            .addComponent(tanggal)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel6)
                        .addGap(291, 291, 291)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(kode_buku1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pilih_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel16)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel8)
                        .addGap(245, 245, 245)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jumlah_buku1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(satuan_1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(total_1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kode_buku1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pilih_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapus))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah_buku1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(satuan_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sub_totalitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(net_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(ppen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sub_totalitas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(receipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cetak)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void satuan_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satuan_1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_satuan_1ActionPerformed

    private void total_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_1ActionPerformed

    private void sub_totalitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_totalitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_totalitasActionPerformed

    private void net_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_net_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_net_totalActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
        Integer bayar = Integer.valueOf(cash.getText());
        Integer angsulan = total - bayar;
        
        kembalian.setText(angsulan.toString());
    }//GEN-LAST:event_cashActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Integer net = Integer.valueOf(net_total.getText());
        Integer bayar = Integer.valueOf(cash.getText());
        Integer angsulan = bayar - net;
        
        kembalian.setText(angsulan.toString());
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
	Date date = new Date();
        tanggal.setText(dateFormat.format(date));
        
        receipt.setText("10104-071084824");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void kode_buku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_buku1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_buku1ActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void pilih_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilih_bukuActionPerformed
        // TODO add your handling code here:
        
        if ((String)pilih_buku.getSelectedItem() == "- none -"){
            satuan_1.setText("");
            kode_buku1.setText("");
        }else if ((String)pilih_buku.getSelectedItem() == "Silence by Akiyoshi Rikako"){
            satuan_1.setText("50000");
            kode_buku1.setText("208010073");
        }else if ((String)pilih_buku.getSelectedItem() == "Jerusalem the Biography by Simon Sebag Montefiore"){
            satuan_1.setText("190000");
            kode_buku1.setText("208010052");
        }else if ((String)pilih_buku.getSelectedItem() == "Guns, Germ and Steel by Jared Diamond"){
            satuan_1.setText("110000");
            kode_buku1.setText("591601251");
        }else if ((String)pilih_buku.getSelectedItem() == "The Human Story by James C. Javis"){
            satuan_1.setText("159000");
            kode_buku1.setText("207993763");
        }else if ((String)pilih_buku.getSelectedItem() == "Pulang by Tere Liye"){
            satuan_1.setText("45000");
            kode_buku1.setText("208039104");
        }else if ((String)pilih_buku.getSelectedItem() == "Art of Dakwah by Felix Siauw"){
            satuan_1.setText("60000");
            kode_buku1.setText("208011233");
        }else if ((String)pilih_buku.getSelectedItem() == "Pemrograman C dan C++ by Adam Mukharil Bachtiar"){
            satuan_1.setText("85000");
            kode_buku1.setText("208531234");
        }else if ((String)pilih_buku.getSelectedItem() == "Kisah Tanah Jawa"){
            satuan_1.setText("99000");
            kode_buku1.setText("208012331");
        }
    }//GEN-LAST:event_pilih_bukuActionPerformed

    private void jumlah_buku1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jumlah_buku1StateChanged
        // TODO add your handling code here:
        int jumlah = (int) jumlah_buku1.getValue();
        int total = jumlah * Integer.valueOf(satuan_1.getText());
        total_1.setText(String.valueOf(total));
    }//GEN-LAST:event_jumlah_buku1StateChanged
    
    private void add_nama(String nama){
        list.setModel(d_nama);
        d_nama.addElement(nama);
    }
    
    private void add_satuan(String satuan){
        sub_total.setModel(d_satuan);
        d_satuan.addElement(satuan);
    }
    private void add_banyak(String banyak){
        banyak_buku.setModel(d_banyak);
        d_banyak.addElement(banyak);
    }
    private void add_subtot(String subtot){
        total_list.setModel(d_subtot);
        d_subtot.addElement(subtot);
    }
    
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        
        
        add_nama((String)pilih_buku.getSelectedItem());
        add_satuan((String)satuan_1.getText());
        add_banyak(String.valueOf(jumlah_buku1.getValue()));
        add_subtot((String)total_1.getText());
        
        
        total = total + Integer.valueOf(total_1.getText());
        sub_totalitas.setText(String.valueOf(total));
        
        int ppn = total * 10 / 100;
        int diskon = 0;
        int dpp = total;
        
        
        if (total > 1000000){
            diskon = total * 10 / 100;
        }
        
        int bkp = total + ppn - diskon;
        
        disk.setText(String.valueOf(diskon));
        ppen.setText(String.valueOf(ppn));
        
        g_ppn = ppn;
        g_disc = diskon;
        g_dpp = dpp;
        g_bkp = bkp;
        
        net_total.setText(String.valueOf(bkp));
        
        jumlah_buku1.setValue(1);
        
        pilih_buku.setSelectedItem("- none -");
       
        babel = babel + 1;
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        total = 0;
        sub_totalitas.setText(String.valueOf(total));
        
        d_nama.clear();
        d_banyak.clear();
        d_satuan.clear();
        d_subtot.clear();
        
        list.setModel(d_nama);
        banyak_buku.setModel(d_banyak);
        sub_total.setModel(d_satuan);
        total_list.setModel(d_subtot);
        
    }//GEN-LAST:event_hapusActionPerformed

    
    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        // TODO add your handling code here:
        print.setVisible(true);
        
        txt_waktu.setText(tanggal.getText());
        txt_kasir.setText(sub_totalitas1.getText());
        txt_receipt.setText(receipt.getText());
        txt_sub.setText(total_1.getText());
        txt_net.setText(net_total.getText());
        txt_cash.setText(cash.getText());
        txt_change.setText(kembalian.getText());
        txt_ppn.setText(String.valueOf(g_ppn));
        txt_bkp.setText(String.valueOf(g_bkp));
        txt_disc.setText(String.valueOf(g_disc));
        txt_dpp.setText(String.valueOf(g_dpp));
        
        int hitung=0;
        while (hitung < babel) {
              String lnama = String.valueOf(d_nama.getElementAt(hitung));
              String lsatuan = String.valueOf(d_satuan.getElementAt(hitung));
              String lbanyak = String.valueOf(d_banyak.getElementAt(hitung));
              String lsubtot = String.valueOf(d_subtot.getElementAt(hitung));
              tampil.setText(tampil.getText()+lnama+"\n"+lbanyak+"\t x"+lsatuan+"\t = "+lsubtot+"\n");
            
//            tampil.setTexte(a_nama[hitung]+"\t"+a_satuan[hitung]+"\t"+a_banyak[hitung]+"\t"+a_subtot[hitung]+"\n");
              hitung = hitung + 1;
        }
            
    }//GEN-LAST:event_cetakActionPerformed

    private void sub_totalitas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_totalitas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_totalitas1ActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void receiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> banyak_buku;
    private javax.swing.JTextField cash;
    private javax.swing.JButton cetak;
    private javax.swing.JTextField disk;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSpinner jumlah_buku1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kode_buku1;
    private javax.swing.JList<String> list;
    private javax.swing.JTextField net_total;
    private javax.swing.JComboBox<String> pilih_buku;
    private javax.swing.JTextField ppen;
    private javax.swing.JDialog print;
    private javax.swing.JTextField receipt;
    private javax.swing.JTextField satuan_1;
    private javax.swing.JList<String> sub_total;
    private javax.swing.JTextField sub_totalitas;
    private javax.swing.JTextField sub_totalitas1;
    private javax.swing.JButton tambah;
    private javax.swing.JTextArea tampil;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField total_1;
    private javax.swing.JList<String> total_list;
    private javax.swing.JLabel txt_bkp;
    private javax.swing.JLabel txt_cash;
    private javax.swing.JLabel txt_change;
    private javax.swing.JLabel txt_disc;
    private javax.swing.JLabel txt_dpp;
    private javax.swing.JLabel txt_kasir;
    private javax.swing.JLabel txt_kasir2;
    private javax.swing.JLabel txt_net;
    private javax.swing.JLabel txt_ppn;
    private javax.swing.JLabel txt_receipt;
    private javax.swing.JLabel txt_receipt1;
    private javax.swing.JLabel txt_sub;
    private javax.swing.JLabel txt_waktu;
    // End of variables declaration//GEN-END:variables
}
